# Generated by Django 3.2 on 2022-05-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loppis', '0002_auto_20220527_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='loppis',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
